name: enote_desk_display
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  firebase_core: ^3.8.1
  firebase_database: ^11.3.5
  intl: ^0.19.0
  shared_preferences: ^2.3.4
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "e_notes.png"
  adaptive_icon_background: "#F5F5DC"  # Your off-white color
  adaptive_icon_foreground: "e_notes.png"  # Black icon on top
  ios_background_color: "#F5F5DC"  # Off-white for iOS too

flutter:
  uses-material-design: true